export type Product = {
  id: string;
  name: string;
  brand: string;
  price: string;
  style: string;
  description: string;
  sizes: string[];
  colours: string[];
  patterns: string[];
  rating?: number;
  reviews?: number;
  emoji?: string;
  image?: string;
  tag?: string;
};

export type Category = {
  id: string;
  name: string;
  icon: string;
  description: string;
  color: string;
  accent: string;
  products: Product[];
};

export const productCategories: Record<string, Category> = {
  electronics: {
    id: "electronics",
    name: "Electronics",
    icon: "\u{1F4F1}",
    description: "The latest in tech - phones, laptops, audio and more.",
    color: "bg-sky-50 border-sky-200",
    accent: "text-sky-600",
    products: [
      {
        id: "macbook-pro-16",
        image: "/products/electronics/macbook-pro-16-v2.jpg",
        name: 'MacBook Pro 16"',
        brand: "Apple",
        price: "$2,499",
        style: "Creative workstation",
        description: "A high-performance laptop for demanding design, video, and development workflows.",
        sizes: ['16"'],
        colours: ["Space Black", "Silver"],
        patterns: ["Solid"],
        rating: 5,
        reviews: 1284,
        emoji: "\u{1F4BB}",
        tag: "Best Seller",
      },
      {
        id: "sony-wh-1000xm5",
        image: "/products/electronics/sony-wh-1000xm5-v2.jpg",
        name: "Sony WH-1000XM5",
        brand: "Sony",
        price: "$279",
        style: "Travel audio",
        description: "Noise-cancelling wireless headphones tuned for long flights, commutes, and focused work.",
        sizes: ["One Size"],
        colours: ["Black", "Silver"],
        patterns: ["Solid"],
        rating: 5,
        reviews: 876,
        emoji: "\u{1F3A7}",
        tag: "Sale",
      },
      {
        id: "iphone-16-pro",
        image: "/products/electronics/iphone-16-pro-v2.jpg",
        name: "iPhone 16 Pro",
        brand: "Apple",
        price: "$1,099",
        style: "Flagship smartphone",
        description: "Premium smartphone with pro-grade camera controls and a polished everyday experience.",
        sizes: ['6.3"'],
        colours: ["Natural Titanium", "Black Titanium", "Desert Titanium"],
        patterns: ["Solid"],
        rating: 5,
        reviews: 3021,
        emoji: "\u{1F4F1}",
        tag: "New",
      },
      {
        id: "ipad-pro-m4",
        image: "/products/electronics/ipad-pro-m4-v2.jpg",
        name: "iPad Pro M4",
        brand: "Apple",
        price: "$999",
        style: "Tablet productivity",
        description: "A slim, powerful tablet built for sketching, media editing, and work on the go.",
        sizes: ['11"', '13"'],
        colours: ["Space Black", "Silver"],
        patterns: ["Solid"],
        rating: 4,
        reviews: 512,
        emoji: "\u{1F4F2}",
      },
      {
        id: "samsung-qled-55",
        image: "/products/electronics/samsung-qled-55-v2.jpg",
        name: 'Samsung QLED 55"',
        brand: "Samsung",
        price: "$799",
        style: "Home entertainment",
        description: "A bright 4K television designed for living rooms, sports nights, and cinematic streaming.",
        sizes: ['55"'],
        colours: ["Titan Gray"],
        patterns: ["Solid"],
        rating: 4,
        reviews: 445,
        emoji: "\u{1F4FA}",
      },
      {
        id: "apple-watch-ultra-2",
        image: "/products/electronics/apple-watch-ultra-2-v2.jpg",
        name: "Apple Watch Ultra 2",
        brand: "Apple",
        price: "$799",
        style: "Adventure wearable",
        description: "A rugged smartwatch with long battery life, precision GPS, and fitness-ready features.",
        sizes: ["49mm"],
        colours: ["Titanium", "Olive"],
        patterns: ["Solid"],
        rating: 5,
        reviews: 699,
        emoji: "\u231A",
        tag: "New",
      },
      {
        id: "bose-quietcomfort-45",
        image: "/products/electronics/bose-quietcomfort-45-v2.jpg",
        name: "Bose QuietComfort 45",
        brand: "Bose",
        price: "$229",
        style: "Comfort audio",
        description: "Soft-cushion headphones that balance all-day comfort with dependable active noise cancellation.",
        sizes: ["One Size"],
        colours: ["Black", "White Smoke"],
        patterns: ["Solid"],
        rating: 4,
        reviews: 387,
        emoji: "\u{1F3A7}",
        tag: "Sale",
      },
      {
        id: "dji-mini-4-pro",
        image: "/products/electronics/dji-mini-4-pro-v2.jpg",
        name: "DJI Mini 4 Pro",
        brand: "DJI",
        price: "$759",
        style: "Aerial camera",
        description: "A compact drone for creators who want stabilized footage without a bulky travel setup.",
        sizes: ["Mini"],
        colours: ["Gray"],
        patterns: ["Solid"],
        rating: 5,
        reviews: 234,
        emoji: "\u{1F6F8}",
      },
    ],
  },
  fashion: {
    id: "fashion",
    name: "Fashion",
    icon: "\u{1F457}",
    description: "Curated clothing, shoes and accessories for every style.",
    color: "bg-rose-50 border-rose-200",
    accent: "text-rose-600",
    products: [
      {
        id: "levis-501-jeans",
        image: "/products/fashion/levis-501-jeans-v2.jpg",
        name: "Levi's 501 Jeans",
        brand: "Levi's",
        price: "$59",
        style: "Classic denim",
        description: "Straight-leg denim with an iconic fit that works across casual and elevated outfits.",
        sizes: ["28", "30", "32", "34", "36"],
        colours: ["Indigo", "Black Wash", "Stone"],
        patterns: ["Solid", "Faded"],
        rating: 5,
        reviews: 2891,
        emoji: "\u{1F456}",
        tag: "Best Seller",
      },
      {
        id: "nike-air-force-1",
        image: "/products/fashion/nike-air-force-1-v2.jpg",
        name: "Nike Air Force 1",
        brand: "Nike",
        price: "$110",
        style: "Streetwear sneaker",
        description: "A timeless low-top sneaker that pairs easily with everyday casual wardrobes.",
        sizes: ["US 7", "US 8", "US 9", "US 10", "US 11"],
        colours: ["White", "Black", "White/Green"],
        patterns: ["Solid", "Contrast Panel"],
        rating: 5,
        reviews: 4102,
        emoji: "\u{1F45F}",
        tag: "Classic",
      },
      {
        id: "oversized-trench",
        image: "/products/fashion/oversized-trench-v2.jpg",
        name: "Oversized Trench",
        brand: "Aureline",
        price: "$149",
        style: "Tailored outerwear",
        description: "A relaxed trench coat designed for layering through cool-weather city dressing.",
        sizes: ["S", "M", "L"],
        colours: ["Camel", "Stone", "Black"],
        patterns: ["Solid"],
        rating: 4,
        reviews: 723,
        emoji: "\u{1F9E5}",
        tag: "Trending",
      },
      {
        id: "silk-slip-dress",
        image: "/products/fashion/silk-slip-dress-v2.jpg",
        name: "Silk Slip Dress",
        brand: "Maison Vale",
        price: "$89",
        style: "Evening minimal",
        description: "A fluid slip dress with a soft sheen that transitions from dinner to events with ease.",
        sizes: ["XS", "S", "M", "L"],
        colours: ["Champagne", "Black", "Rose"],
        patterns: ["Solid"],
        rating: 4,
        reviews: 441,
        emoji: "\u{1F457}",
      },
      {
        id: "canvas-tote-bag",
        image: "/products/fashion/canvas-tote-bag-v2.jpg",
        name: "Canvas Tote Bag",
        brand: "North Harbor",
        price: "$35",
        style: "Utility casual",
        description: "A roomy everyday tote with durable canvas construction and a clean modern shape.",
        sizes: ["One Size"],
        colours: ["Natural", "Olive", "Navy"],
        patterns: ["Solid", "Stripe"],
        rating: 5,
        reviews: 1120,
        emoji: "\u{1F45C}",
        tag: "New",
      },
      {
        id: "merino-wool-sweater",
        image: "/products/fashion/merino-wool-sweater-v2.jpg",
        name: "Merino Wool Sweater",
        brand: "Hearth & Thread",
        price: "$120",
        style: "Cold-weather knit",
        description: "Fine merino knitwear with a polished finish for workdays, layering, and travel.",
        sizes: ["S", "M", "L", "XL"],
        colours: ["Oatmeal", "Forest", "Navy"],
        patterns: ["Solid", "Ribbed"],
        rating: 5,
        reviews: 632,
        emoji: "\u{1F9E3}",
      },
      {
        id: "aviator-sunglasses",
        image: "/products/fashion/aviator-sunglasses-v2.jpg",
        name: "Aviator Sunglasses",
        brand: "Solstice",
        price: "$75",
        style: "Warm-weather accessory",
        description: "Lightweight metal-frame sunglasses with a classic aviator silhouette and tinted lenses.",
        sizes: ["One Size"],
        colours: ["Gold", "Silver", "Black"],
        patterns: ["Solid", "Gradient Lens"],
        rating: 4,
        reviews: 881,
        emoji: "\u{1F576}",
      },
      {
        id: "gold-hoop-earrings",
        image: "/products/fashion/gold-hoop-earrings-v2.jpg",
        name: "Gold Hoop Earrings",
        brand: "Lune Studio",
        price: "$45",
        style: "Everyday jewelry",
        description: "Polished hoop earrings that add a simple statement to both casual and dressy looks.",
        sizes: ["Small", "Medium", "Large"],
        colours: ["Gold", "Silver"],
        patterns: ["Solid"],
        rating: 5,
        reviews: 556,
        emoji: "\u{1F48D}",
        tag: "Sale",
      },
    ],
  },
  home: {
    id: "home",
    name: "Home & Living",
    icon: "\u{1F3E1}",
    description: "Transform your space with furniture, decor and kitchen essentials.",
    color: "bg-amber-50 border-amber-200",
    accent: "text-amber-600",
    products: [
      {
        id: "linen-sofa-3-seat",
        image: "/products/home/linen-sofa-3-seat-v2.jpg",
        name: "Linen Sofa 3-Seat",
        brand: "Foundry Home",
        price: "$899",
        style: "Modern living room",
        description: "A softly structured sofa with clean lines and plush cushioning for relaxed living spaces.",
        sizes: ["3-Seat"],
        colours: ["Sand", "Fog", "Olive"],
        patterns: ["Solid"],
        rating: 5,
        reviews: 342,
        emoji: "\u{1F6CB}",
        tag: "Best Seller",
      },
      {
        id: "dyson-v15-vacuum",
        image: "/products/home/dyson-v15-vacuum-v2.jpg",
        name: "Dyson V15 Vacuum",
        brand: "Dyson",
        price: "$549",
        style: "Smart cleaning",
        description: "A cordless vacuum with strong suction and smart sensing for quick whole-home cleaning.",
        sizes: ["Standard"],
        colours: ["Nickel", "Yellow"],
        patterns: ["Solid"],
        rating: 5,
        reviews: 1203,
        emoji: "\u{1F9F9}",
        tag: "Sale",
      },
      {
        id: "coffee-maker-pro",
        image: "/products/home/coffee-maker-pro-v2.jpg",
        name: "Coffee Maker Pro",
        brand: "Brewline",
        price: "$129",
        style: "Kitchen essential",
        description: "Programmable coffee maker built for dependable morning routines and weekend hosting.",
        sizes: ["12-Cup"],
        colours: ["Matte Black", "Cream"],
        patterns: ["Solid"],
        rating: 4,
        reviews: 877,
        emoji: "\u2615",
      },
      {
        id: "pendant-light-set",
        image: "/products/home/pendant-light-set-v2.jpg",
        name: "Pendant Light Set",
        brand: "Halo House",
        price: "$199",
        style: "Ambient lighting",
        description: "A coordinated pendant set that adds warm modern lighting above islands and dining tables.",
        sizes: ["Set of 3"],
        colours: ["Brass", "Black"],
        patterns: ["Solid"],
        rating: 4,
        reviews: 445,
        emoji: "\u{1F4A1}",
        tag: "New",
      },
      {
        id: "cast-iron-dutch-oven",
        image: "/products/home/cast-iron-dutch-oven-v2.jpg",
        name: "Cast Iron Dutch Oven",
        brand: "Maison Cook",
        price: "$89",
        style: "Cookware classic",
        description: "Heavy-duty enamel cookware built for slow braises, breads, and hearty family meals.",
        sizes: ["4 qt", "6 qt"],
        colours: ["Cherry", "Navy", "Cream"],
        patterns: ["Solid"],
        rating: 5,
        reviews: 2011,
        emoji: "\u{1F372}",
        tag: "Best Seller",
      },
      {
        id: "bamboo-bookshelf",
        image: "/products/home/bamboo-bookshelf-v2.jpg",
        name: "Bamboo Bookshelf",
        brand: "Kin Grove",
        price: "$249",
        style: "Natural storage",
        description: "An open shelving unit with warm bamboo tones for books, plants, and display pieces.",
        sizes: ["5 Shelf"],
        colours: ["Natural", "Walnut"],
        patterns: ["Wood Grain"],
        rating: 4,
        reviews: 321,
        emoji: "\u{1F4DA}",
      },
      {
        id: "smart-thermostat",
        image: "/products/home/smart-thermostat-v2.jpg",
        name: "Smart Thermostat",
        brand: "Nest",
        price: "$179",
        style: "Connected comfort",
        description: "A smart thermostat that helps automate temperature control and save energy at home.",
        sizes: ["Standard"],
        colours: ["Snow", "Sand", "Charcoal"],
        patterns: ["Solid"],
        rating: 5,
        reviews: 654,
        emoji: "\u{1F321}",
        tag: "New",
      },
      {
        id: "scented-candle-set",
        image: "/products/home/scented-candle-set-v2.jpg",
        name: "Scented Candle Set",
        brand: "Quiet Corner",
        price: "$49",
        style: "Atmosphere decor",
        description: "A curated candle trio designed to bring soft fragrance and warmth into shared spaces.",
        sizes: ["Set of 3"],
        colours: ["Ivory", "Amber"],
        patterns: ["Solid", "Etched"],
        rating: 5,
        reviews: 1440,
        emoji: "\u{1F56F}",
        tag: "Trending",
      },
    ],
  },
  beauty: {
    id: "beauty",
    name: "Beauty",
    icon: "\u2728",
    description: "Skincare, makeup and wellness products you'll love.",
    color: "bg-fuchsia-50 border-fuchsia-200",
    accent: "text-fuchsia-600",
    products: [
      {
        id: "cosrx-ha-serum",
        image: "/products/beauty/cosrx-ha-serum-v2.jpg",
        name: "COSRX HA Serum",
        brand: "COSRX",
        price: "$23",
        style: "Hydration skincare",
        description: "A lightweight serum focused on daily hydration, bounce, and soothing moisture support.",
        sizes: ["30ml", "50ml"],
        colours: ["Clear"],
        patterns: ["Glossy"],
        rating: 5,
        reviews: 3421,
        emoji: "\u{1F9F4}",
        tag: "Best Seller",
      },
      {
        id: "vitamin-c-moisturizer",
        image: "/products/beauty/vitamin-c-moisturizer-v2.jpg",
        name: "Vitamin C Moisturizer",
        brand: "Glow Theory",
        price: "$42",
        style: "Brightening skincare",
        description: "A daily moisturizer with a brightening feel and smooth finish for morning routines.",
        sizes: ["50ml"],
        colours: ["Cream"],
        patterns: ["Solid"],
        rating: 5,
        reviews: 1102,
        emoji: "\u{1F9F4}",
        tag: "New",
      },
      {
        id: "spf50-sunscreen",
        image: "/products/beauty/spf50-sunscreen-v2.jpg",
        name: "SPF50 Sunscreen",
        brand: "Sunveil",
        price: "$18",
        style: "Daily protection",
        description: "Broad-spectrum sunscreen designed for easy daily wear without a heavy white cast.",
        sizes: ["50ml", "100ml"],
        colours: ["Sheer"],
        patterns: ["Solid"],
        rating: 5,
        reviews: 2877,
        emoji: "\u2600",
        tag: "Best Seller",
      },
      {
        id: "rose-face-mist",
        image: "/products/beauty/rose-face-mist-v2.jpg",
        name: "Rose Face Mist",
        brand: "Botanica",
        price: "$29",
        style: "Refresh skincare",
        description: "A refreshing mist for mid-day hydration, glow prep, and post-cleanse comfort.",
        sizes: ["100ml"],
        colours: ["Rose"],
        patterns: ["Floral"],
        rating: 4,
        reviews: 654,
        emoji: "\u{1F339}",
      },
      {
        id: "retinol-night-cream",
        image: "/products/beauty/retinol-night-cream-v2.jpg",
        name: "Retinol Night Cream",
        brand: "Dermaline",
        price: "$55",
        style: "Overnight care",
        description: "A rich evening cream intended for smoothing texture and supporting a refined nighttime routine.",
        sizes: ["50ml"],
        colours: ["Lavender"],
        patterns: ["Solid"],
        rating: 5,
        reviews: 1341,
        emoji: "\u{1F31C}",
        tag: "Trending",
      },
      {
        id: "chanel-no-5-50ml",
        image: "/products/beauty/chanel-no-5-50ml-v2.jpg",
        name: "Chanel No. 5 (50ml)",
        brand: "Chanel",
        price: "$89",
        style: "Signature fragrance",
        description: "An iconic fragrance with a polished, timeless profile for special occasions or everyday wear.",
        sizes: ["50ml", "100ml"],
        colours: ["Amber"],
        patterns: ["Solid"],
        rating: 5,
        reviews: 4120,
        emoji: "\u{1F490}",
        tag: "Classic",
      },
      {
        id: "mascara-extreme",
        image: "/products/beauty/mascara-extreme-v2.jpg",
        name: "Mascara Extreme",
        brand: "Velour",
        price: "$22",
        style: "Eye definition",
        description: "A volumizing mascara for bold lashes with a buildable finish and lightweight feel.",
        sizes: ["One Size"],
        colours: ["Black", "Brown"],
        patterns: ["Solid"],
        rating: 4,
        reviews: 891,
        emoji: "\u{1F484}",
      },
      {
        id: "lip-gloss-set",
        image: "/products/beauty/lip-gloss-set-v2.jpg",
        name: "Lip Gloss Set",
        brand: "Tint Lab",
        price: "$35",
        style: "Shine makeup",
        description: "A glossy multi-shade set designed for layering, gifting, and quick on-the-go touchups.",
        sizes: ["Set of 4"],
        colours: ["Rose", "Berry", "Peach"],
        patterns: ["Solid", "Shimmer"],
        rating: 4,
        reviews: 702,
        emoji: "\u{1F484}",
        tag: "Sale",
      },
    ],
  },
  sports: {
    id: "sports",
    name: "Sports",
    icon: "\u{1F3C3}",
    description: "Gear up with top-rated sports equipment and activewear.",
    color: "bg-emerald-50 border-emerald-200",
    accent: "text-emerald-600",
    products: [
      {
        id: "yoga-mat-pro",
        image: "/products/sports/yoga-mat-pro-v2.jpg",
        name: "Yoga Mat Pro",
        brand: "FlowForm",
        price: "$65",
        style: "Studio training",
        description: "A supportive, grippy yoga mat built for home sessions, stretching, and studio practice.",
        sizes: ["Standard", "Long"],
        colours: ["Sage", "Charcoal", "Lilac"],
        patterns: ["Solid", "Marble"],
        rating: 5,
        reviews: 2341,
        emoji: "\u{1F9D8}",
        tag: "Best Seller",
      },
      {
        id: "adjustable-dumbbells",
        image: "/products/sports/adjustable-dumbbells-v2.jpg",
        name: "Adjustable Dumbbells",
        brand: "Iron Core",
        price: "$189",
        style: "Strength training",
        description: "Space-saving dumbbells with adjustable resistance for progressive home workouts.",
        sizes: ["25 lb", "50 lb"],
        colours: ["Black", "Red"],
        patterns: ["Solid"],
        rating: 5,
        reviews: 987,
        emoji: "\u{1F4AA}",
        tag: "New",
      },
      {
        id: "running-shoes-v2",
        image: "/products/sports/running-shoes-v2-asset.jpg",
        name: "Running Shoes V2",
        brand: "Stridelab",
        price: "$130",
        style: "Performance running",
        description: "A cushioned running shoe tuned for daily mileage, tempo sessions, and comfortable recovery days.",
        sizes: ["US 7", "US 8", "US 9", "US 10", "US 11"],
        colours: ["White/Blue", "Black/Lime", "Coral"],
        patterns: ["Color Block", "Solid"],
        rating: 5,
        reviews: 1450,
        emoji: "\u{1F45F}",
        tag: "Trending",
      },
      {
        id: "cycling-helmet",
        image: "/products/sports/cycling-helmet-v2.jpg",
        name: "Cycling Helmet",
        brand: "AeroTrail",
        price: "$79",
        style: "Road safety",
        description: "A lightweight helmet with ample ventilation for safer commutes and long weekend rides.",
        sizes: ["S", "M", "L"],
        colours: ["Matte Black", "White", "Cyan"],
        patterns: ["Solid"],
        rating: 4,
        reviews: 556,
        emoji: "\u26D1",
      },
      {
        id: "resistance-bands-set",
        image: "/products/sports/resistance-bands-set-v2.jpg",
        name: "Resistance Bands Set",
        brand: "Coreline",
        price: "$35",
        style: "Portable fitness",
        description: "A compact resistance band kit suited for mobility work, travel workouts, and warm-ups.",
        sizes: ["Light", "Medium", "Heavy"],
        colours: ["Yellow", "Blue", "Black"],
        patterns: ["Solid"],
        rating: 5,
        reviews: 3201,
        emoji: "\u{1F4AA}",
        tag: "Best Seller",
      },
      {
        id: "swimming-goggles",
        image: "/products/sports/swimming-goggles-v2.jpg",
        name: "Swimming Goggles",
        brand: "Blue Current",
        price: "$29",
        style: "Pool essential",
        description: "Leak-resistant goggles with anti-fog lenses for regular lap swimming and training sessions.",
        sizes: ["Adult"],
        colours: ["Smoke", "Blue", "Clear"],
        patterns: ["Solid"],
        rating: 4,
        reviews: 441,
        emoji: "\u{1F3CA}",
      },
      {
        id: "protein-powder-2kg",
        image: "/products/sports/protein-powder-2kg-v2.jpg",
        name: "Protein Powder 2kg",
        brand: "Peak Fuel",
        price: "$55",
        style: "Recovery nutrition",
        description: "A versatile protein blend for post-workout recovery shakes and everyday supplementation.",
        sizes: ["2kg"],
        colours: ["Vanilla", "Chocolate"],
        patterns: ["Solid"],
        rating: 5,
        reviews: 2110,
        emoji: "\u{1F964}",
        tag: "Sale",
      },
      {
        id: "jump-rope-pro",
        image: "/products/sports/jump-rope-pro-v2.jpg",
        name: "Jump Rope Pro",
        brand: "TempoFit",
        price: "$22",
        style: "Cardio training",
        description: "A speed rope with smooth bearings for quick cardio circuits and warmup routines.",
        sizes: ["Standard"],
        colours: ["Black", "Red", "Blue"],
        patterns: ["Solid"],
        rating: 5,
        reviews: 1780,
        emoji: "\u{1FAE0}",
      },
    ],
  },
  books: {
    id: "books",
    name: "Books & Media",
    icon: "\u{1F4DA}",
    description: "Bestselling books, music, games and digital media.",
    color: "bg-violet-50 border-violet-200",
    accent: "text-violet-600",
    products: [
      {
        id: "atomic-habits",
        image: "/products/books/atomic-habits-v2.jpg",
        name: "Atomic Habits",
        brand: "Avery",
        price: "$17",
        style: "Personal development",
        description: "A widely loved habits book focused on consistent systems and sustainable personal change.",
        sizes: ["Paperback", "Hardcover"],
        colours: ["White", "Gold"],
        patterns: ["Text Cover"],
        rating: 5,
        reviews: 12450,
        emoji: "\u{1F4D8}",
        tag: "Best Seller",
      },
      {
        id: "the-midnight-library",
        image: "/products/books/the-midnight-library-v2.jpg",
        name: "The Midnight Library",
        brand: "Canongate",
        price: "$14",
        style: "Contemporary fiction",
        description: "A popular novel that blends reflection, emotion, and alternate-life storytelling.",
        sizes: ["Paperback", "Hardcover"],
        colours: ["Blue", "Navy"],
        patterns: ["Illustrated"],
        rating: 5,
        reviews: 5310,
        emoji: "\u{1F4D6}",
        tag: "Trending",
      },
      {
        id: "taylor-swift-vinyl",
        image: "/products/books/taylor-swift-vinyl-v2.jpg",
        name: "Taylor Swift Vinyl",
        brand: "Republic Records",
        price: "$29",
        style: "Collector audio",
        description: "A display-worthy vinyl release for music lovers building a curated home listening setup.",
        sizes: ["12 in"],
        colours: ["Black", "Marbled Blue"],
        patterns: ["Solid", "Marbled"],
        rating: 5,
        reviews: 3201,
        emoji: "\u{1F3B5}",
        tag: "New",
      },
      {
        id: "catan-board-game",
        image: "/products/books/catan-board-game-v2.jpg",
        name: "Catan Board Game",
        brand: "Catan Studio",
        price: "$44",
        style: "Game night",
        description: "A strategic board game staple for family nights and competitive group sessions.",
        sizes: ["Standard"],
        colours: ["Multi"],
        patterns: ["Illustrated"],
        rating: 5,
        reviews: 7821,
        emoji: "\u{1F3B2}",
        tag: "Classic",
      },
      {
        id: "dune-boxed-set",
        image: "/products/books/dune-boxed-set-v2.jpg",
        name: "Dune (Boxed Set)",
        brand: "Ace",
        price: "$39",
        style: "Sci-fi collection",
        description: "A boxed set for readers who want to dive deep into an iconic science-fiction universe.",
        sizes: ["Boxed Set"],
        colours: ["Black", "Sand"],
        patterns: ["Illustrated"],
        rating: 5,
        reviews: 4102,
        emoji: "\u{1F4DA}",
      },
      {
        id: "art-of-war",
        image: "/products/books/art-of-war-v2.jpg",
        name: "Art of War",
        brand: "Penguin Classics",
        price: "$9",
        style: "Classic strategy",
        description: "A concise strategy classic that remains popular across leadership and history readers.",
        sizes: ["Paperback"],
        colours: ["Black", "Red"],
        patterns: ["Text Cover"],
        rating: 4,
        reviews: 6711,
        emoji: "\u2694",
      },
      {
        id: "kindle-paperwhite",
        image: "/products/books/kindle-paperwhite-v2.jpg",
        name: "Kindle Paperwhite",
        brand: "Amazon",
        price: "$139",
        style: "Digital reading",
        description: "A lightweight e-reader with a crisp display and long battery life for distraction-free reading.",
        sizes: ['6.8"'],
        colours: ["Black", "Denim", "Agave"],
        patterns: ["Solid"],
        rating: 5,
        reviews: 9021,
        emoji: "\u{1F4D6}",
        tag: "Best Seller",
      },
      {
        id: "jigsaw-puzzle-1000pc",
        image: "/products/books/jigsaw-puzzle-1000pc-v2.jpg",
        name: "Jigsaw Puzzle 1000pc",
        brand: "Piece & Pine",
        price: "$18",
        style: "Leisure tabletop",
        description: "A detailed 1000-piece puzzle made for calm weekends, gifting, and shared downtime.",
        sizes: ["1000 Pieces"],
        colours: ["Multi"],
        patterns: ["Landscape", "Abstract"],
        rating: 4,
        reviews: 1201,
        emoji: "\u{1F9E9}",
        tag: "Sale",
      },
    ],
  },
};

export const tagColors: Record<string, string> = {
  "Best Seller": "bg-amber-100 text-amber-700",
  New: "bg-emerald-100 text-emerald-700",
  Sale: "bg-red-100 text-red-700",
  Trending: "bg-indigo-100 text-indigo-700",
  Classic: "bg-zinc-100 text-zinc-700",
};

export const sortOptions = [
  "Featured",
  "Price: Low to High",
  "Price: High to Low",
  "Best Rated",
] as const;

export type SortOption = (typeof sortOptions)[number];

export function getCategoryById(categoryId: string) {
  return productCategories[categoryId];
}

export function getProductById(categoryId: string, productId: string) {
  return productCategories[categoryId]?.products.find(
    (product) => product.id === productId,
  );
}

export function parsePrice(price: string) {
  return Number(price.replace(/[^0-9.]/g, ""));
}
